### ISSUE TITLE
tests are not working on my system

### ISSUE THREAD

**Issue by smhx** [adtac/fssb#8]
I cloned the repo, ran make, and then ./launch_tests.sh. I got this output:
```
[steven@lzyrbt tests]$ sudo ./launch_tests.sh
Removing all /tmp/fssb-*
Launching tests
Launching test on test_no_syscalls
fssb: child exited with 0
fssb: sandbox directory: /tmp/fssb-1/
Launching check on test_no_syscalls
Assert in line 84 passed: check_no_syscalls
Launching test on test_save_empty_file
fssb: child exited with 0
fssb: sandbox directory: /tmp/fssb-2/
Launching check on test_save_empty_file
Assert in line 108 failed: check_save_empty_file
args = ('', '/tmp/fssb-2/f61bd54ddf9c9dce6076a3c8a7892e49 = save_empty_file\n')
kwargs = {}
            '{} = {}\n'.format(empty_file_path, empty_file_name)

Traceback (most recent call last):
  File "./tests.py", line 145, in <module>
    main()
  File "./tests.py", line 134, in main
    test_check()
  File "./tests.py", line 110, in check_save_empty_file
    _assert(operator.eq, open(empty_file_path).read(), '')
IOError: [Errno 2] No such file or directory: '/tmp/fssb-2/f61bd54ddf9c9dce6076a3c8a7892e49'
```
I then compiled the code below as main.cpp:
```
#include <cstdio>

int main() {
    freopen("myfile.txt", "w", stdout);
    printf("Hello world\n");
}
```
I added printf statements in handle_syscalls in fssb.c. In the switch statement, I printed the current syscall (and relevant variables like pathname). I ran fssb on ./main and got:
```
[steven@lzyrbt tests]$ ../fssb -m -- ./main
handling syscall = SYS_access with pathname = /etc/ld.so.preload
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/tls/haswell/x86_64
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/tls/haswell
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/tls/x86_64
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/tls
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/haswell/x86_64
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/haswell
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/x86_64
handling syscall = SYS_exit_group
fssb: child exited with 0
fssb: sandbox directory: /tmp/fssb-3/
```
In addition, the file tests/myfile.txt was created and it contains "Hello world\n"

What is going on?

**Comment by smhx** [comment]
Update:
I added a default: to the switch statement in handle_syscalls that prints unhandled syscalls.
I got this output:
```
[steven@lzyrbt tests]$ ../fssb -- ./main
Unhandled syscall = 59
Unhandled syscall = 59
Unhandled syscall = 12
Unhandled syscall = 12
handling syscall = SYS_access with pathname = /etc/ld.so.preload
Unhandled syscall = 257
Unhandled syscall = 257
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/tls/haswell/x86_64
Unhandled syscall = 257
Unhandled syscall = 257
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/tls/haswell
Unhandled syscall = 257
Unhandled syscall = 257
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/tls/x86_64
Unhandled syscall = 257
Unhandled syscall = 257
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/tls
Unhandled syscall = 257
Unhandled syscall = 257
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/haswell/x86_64
Unhandled syscall = 257
Unhandled syscall = 257
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/haswell
Unhandled syscall = 257
Unhandled syscall = 257
handling syscall = SYS_stat
handling syscall = SYS_lstat
handling syscall = SYS_access with pathname = /usr/lib/x86_64
Unhandled syscall = 257
Unhandled syscall = 257
Unhandled syscall = 0
Unhandled syscall = 0
Unhandled syscall = 5
Unhandled syscall = 5
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 3
Unhandled syscall = 3
Unhandled syscall = 257
Unhandled syscall = 257
Unhandled syscall = 0
Unhandled syscall = 0
Unhandled syscall = 5
Unhandled syscall = 5
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 3
Unhandled syscall = 3
Unhandled syscall = 257
Unhandled syscall = 257
Unhandled syscall = 0
Unhandled syscall = 0
Unhandled syscall = 5
Unhandled syscall = 5
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 3
Unhandled syscall = 3
Unhandled syscall = 257
Unhandled syscall = 257
Unhandled syscall = 0
Unhandled syscall = 0
Unhandled syscall = 5
Unhandled syscall = 5
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 3
Unhandled syscall = 3
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 158
Unhandled syscall = 158
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 9
Unhandled syscall = 9
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 10
Unhandled syscall = 12
Unhandled syscall = 12
Unhandled syscall = 12
Unhandled syscall = 12
Unhandled syscall = 257
Unhandled syscall = 257
Unhandled syscall = 292
Unhandled syscall = 292
Unhandled syscall = 3
Unhandled syscall = 3
Unhandled syscall = 5
Unhandled syscall = 5
Unhandled syscall = 1
Unhandled syscall = 1
handling syscall = SYS_exit_group
fssb: child exited with 0
fssb: sandbox directory: /tmp/fssb-7/
```

**Comment by smhx** [comment]
The tests work when i copy the code from SYS_creat to a new case SYS_openat except the path arg is now 1 and the flag arg is now 2. I don't know if this creates new problems or works in all cases though...
